### ISSUE TITLE
Max Depth and Depth Format

### ISSUE THREAD

**Issue by Nimesh112** [iro-cp/FCRN-DepthPrediction#25]
Hello.

I was just wondering what the maximum depth your model can reliably predict is. Also is your depth format linear or log scale? 

Thanks

**Comment by iro-cp** [comment]
Hi. The maximum depth that can be predicted for the indoor model is ~10m, because that's the maximum distance recorded in the dataset (NYU-Depth v2). The maximum depth for the outdoor model is ~70m (based on Make3D). In either case, the distances produced by the models are in meters, as we did not train with log scale.

**Comment by Nimesh112** [comment]
Okay thanks.
