### ISSUE TITLE
 tensoflow script

### ISSUE THREAD

**Issue by oneOfThePeople** [iro-cp/FCRN-DepthPrediction#9]
can you add please to predict.py resize the image like matlab?
and if i understand right the neural network can get maximum 640,480 image size?
thanks

**Comment by iro-cp** [comment]
Hi, thanks for the comment! I will add it :) The TensorFlow version is still under development and thus subject to changes and improvements. 

The network input can be of any size, because the model is fully convolutional. However it works best when the input image is close to the size and aspect ratio the network was trained with. If it's too large, for example, the predicted depth maps might be a bit distorted and not very accurate.

**Comment by oneOfThePeople** [comment]
it's worked great and without any problem. beautiful ,thank :)

**Comment by iro-cp** [comment]
thanks, it should be fixed now :)
